color: null
fieldLayouts:
  d26dc4bf-8333-4978-b105-f383551cdd12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-29T13:37:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cbb09bcf-1696-4922-a2dc-547a8cac6645
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-29T13:40:32+00:00'
            elementCondition: null
            fieldUid: e85b1053-409d-4874-8136-0253a2c94862 # Publishing or Showcase Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f45c2232-7e93-4465-b46b-6e89341eda4f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-29T13:41:43+00:00'
            elementCondition: null
            fieldUid: 7a9eddca-3108-4430-9030-e003f11e45c5 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57229dcb-6d15-418d-88f3-4a08cfdf73e4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-29T14:06:19+00:00'
            elementCondition: null
            fieldUid: da68aa9e-9c82-430e-9938-1f3eb161981c # External Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d44ce28-26b8-4386-be0e-c42be95d235c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e77be274-a61a-4fd2-9d21-85114c0681ea
        userCondition: null
handle: date
hasTitleField: true
icon: null
name: Date
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
