color: null
fieldLayouts:
  8a60d25b-4992-41f8-bcf1-066de6374a4e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-09T20:07:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9cae8fef-30d6-4a29-89bf-9114ca3b076d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T22:09:48+00:00'
            elementCondition: null
            fieldUid: a3cd7fd4-adda-4bd5-ad5e-f3ca6b60f9fa # Home Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e358230-9223-474f-b5fb-8229331fca23
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T22:09:48+00:00'
            elementCondition: null
            fieldUid: 982a374f-5ed2-4c17-8d44-3a783aafbbdb # Home Highlighted
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5daa451d-792c-4b30-b0f9-6c561f044cca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b7108049-e148-4c2c-81ad-9cb726026f6d
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
