color: null
fieldLayouts:
  6125da87-f462-48d0-bec8-3a46cf77ccda:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-29T13:57:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20d4f2cf-e9fc-48fd-b3b0-b1bcda56cfa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-29T13:59:34+00:00'
            elementCondition: null
            fieldUid: 93eeb673-38e7-4908-b833-dc48fcea85ba # Photos
            handle: photos
            includeInCards: false
            instructions: null
            label: Photos
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24922937-89aa-41f1-89fd-328ed5c9e74f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00d772e1-ca7d-45ef-aca4-40334ff07f08
        userCondition: null
handle: photoDocumentation
hasTitleField: true
icon: null
name: 'Photo Documentation'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
