color: null
fieldLayouts:
  b73f7a4f-7a22-4981-8db6-3e16ad1422a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-29T13:25:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab93efb0-bea8-4559-a028-878a9f240fd2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-29T13:27:36+00:00'
            elementCondition: null
            fieldUid: 75e77eb5-3461-415a-ae31-1d8ff80df435
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6d6d38a-e5cb-4bae-b161-3e3318d2a452
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f7bed17-7081-4759-89c6-33c066e647e3
        userCondition: null
handle: presentationDate
hasTitleField: true
icon: null
name: 'Date of Presentation'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
