color: null
fieldLayouts:
  ae142d20-e0c8-4704-a551-55772a4b4290:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-09T20:37:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77b51b65-485e-4d2f-a5fc-1835223021ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-09T21:03:57+00:00'
            elementCondition: null
            fieldUid: a93c6dfd-51a9-4a7c-892e-17f9507ceebf # Main Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12f99f97-e1c4-4432-9e6d-31744328c1de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-09T21:03:57+00:00'
            elementCondition: null
            fieldUid: 7a9eddca-3108-4430-9030-e003f11e45c5 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 469c107c-faa6-4cef-9607-02f3de8bcece
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91d27345-eab1-43b9-be85-6c57bbe78274
        userCondition: null
handle: works
hasTitleField: true
icon: ''
name: Works
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
