defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2e66a0a9-7e7f-40b9-81b7-65f65b6ccdbb # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7dd3e362-d5d2-415e-aaed-53812590be80: # Maren Stockloew
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
